module.exports = {
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 2017,
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true
    }
  },
  env: {
    es6: true,
    node: true
  },
  extends: ['eslint:recommended', 'plugin:promise/recommended', 'plugin:node/recommended', 'plugin:import/warnings', 'plugin:import/errors'],
  plugins: ['promise', 'import', 'node'],
  rules: {
    'no-empty': 'error',
    'no-ex-assign': 'error',
    'no-func-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-regex-spaces': 'error',
    'no-sparse-arrays': 'error',
    'no-unexpected-multiline': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'class-methods-use-this': 'error',
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'no-case-declarations': 'error',
    'no-div-regex': 'error',
    'no-empty-function': 'error',
    'no-eq-null': 'error',
    'no-extra-bind': 'error',
    'no-floating-decimal': 'error',
    'no-invalid-this': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-new-func': 'error',
    'no-redeclare': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': 'warn',
    'no-useless-call': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'prefer-promise-reject-errors': 'error',
    yoda: ['error', 'never'],
    'no-catch-shadow': 'error',
    'no-delete-var': 'error',
    'no-shadow-restricted-names': 'error',
    'no-undef-init': 'error',
    'no-unused-vars': 'warn',
    'no-use-before-define': 'error',
    'global-require': 'error',
    'no-new-require': 'error',
    'no-path-concat': 'error',
    'array-bracket-spacing': ['error', 'never'],
    'computed-property-spacing': ['error', 'never'],
    'block-spacing': ['error', 'always'],
    'func-call-spacing': ['error', 'never'],
    'brace-style': ['error', '1tbs', { allowSingleLine: true }],
    camelcase: ['error', { properties: 'always' }],
    'comma-dangle': ['warn', 'never'],
    'comma-spacing': ['warn', { before: false, after: true }],
    'comma-style': ['warn', 'last'],
    'func-name-matching': 'error',
    'key-spacing': ['error', { beforeColon: false, afterColon: true }],
    'keyword-spacing': ['error', { after: true, before: true }],
    'lines-around-comment': [
      'error',
      {
        beforeLineComment: true,
        allowBlockStart: true,
        afterBlockComment: true,
        beforeBlockComment: true
      }
    ],
    'lines-around-directive': ['error', 'always'],
    'max-depth': ['error', { max: 7 }],
    'max-nested-callbacks': ['error', { max: 4 }],
    'newline-after-var': ['error', 'always'],
    'newline-before-return': 'error',
    'no-continue': 'error',
    'no-mixed-operators': 'error',
    'no-multiple-empty-lines': ['error', { max: 1 }],
    'no-nested-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'object-curly-spacing': ['error', 'always'],
    'operator-linebreak': ['error', 'none'],
    'padded-blocks': ['error', 'never'],
    'semi-spacing': ['error', { before: false, after: true }],
    semi: ['error', 'always'],
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-spacing': ['error', { before: true, after: true }],
    'generator-star-spacing': ['error', { before: true, after: false }],
    'no-confusing-arrow': 'error',
    'no-duplicate-imports': 'error',
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'object-shorthand': ['error', 'always', { avoidQuotes: true }],
    'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: false }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'rest-spread-spacing': ['error', 'never'],
    'yield-star-spacing': ['error', 'after'],
    'jsx-quotes': ['error', 'prefer-single']
  }
};
